### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by deepai-lab** [aaronzguan/Face-Recognition-Flask-GUI#2]
Hi, I am getting error while run the app. Can please advise me how to run the app and what are files that I need to run this code?
Thanks in advanced.

**Comment by aaronzguan** [comment]
I would suggest checking if the server for the Flask web service, the path of the database, and the trained models are correct. I didn't put my trained models in the repo but you can find some at [here](https://drive.google.com/drive/folders/1nOY8AhJT2Cf-sQZxviMOFUF05nS4TnfU?usp=sharing). Running api.py directly would be fine. You may post your error here.
